#!/usr/bin/env python
import argparse
import os
import time
from pathlib import Path
import pickle
import pandas as pd
try:
    from . import ask as ask_core
except ImportError:  # Allow direct script execution: python ask/ask_cmd.py ...
    import ask as ask_core
try:
    from .sc_matrix import clean_barcode_columns, write_sc_matrices_if_single_cell
except ImportError:  # Allow direct script execution: python ask/ask_cmd.py ...
    from sc_matrix import clean_barcode_columns, write_sc_matrices_if_single_cell
try:
    from .ask_utils import (
        plot_ask_amplicons,
        prepare_ask_output_paths,
        resolve_ask_annotation_files,
        write_ask_stats,
    )
except ImportError:  # Allow direct script execution: python ask/ask_cmd.py ...
    from ask_utils import (
        plot_ask_amplicons,
        prepare_ask_output_paths,
        resolve_ask_annotation_files,
        write_ask_stats,
    )


#------------------------------------------------------------------------------#
def get_args():
    """ input arguments
    """
    parser = argparse.ArgumentParser(
        description='Seek amplicons from ChIP-seq data')

    parser.add_argument('-i', '--bamfile', required=True,
        help="input bam file, also need the index file in the same folder, \
              which is generated by: samtools index <in.bam>. \
              Recommended to be deduplicated by: samtools markdup")
    parser.add_argument('-g', '--genome', default='hg38',
        help="genome work on (hg19 or hg38, default: hg38)")
    parser.add_argument('-o', '--outprefix',
        help="output file prefix, could include folder")
    parser.add_argument('-b', '--bwfile',
        help="input bigwig file, not currently in use")  # ?????????
    parser.add_argument('-w', '--binsize', type=int, default=10000,
        help="bin size for copy number segmentation")
    parser.add_argument('-c', '--mincn', type=float, default=5,
        help="minimal absolute copy number of bins to be considered \
              as amplicons; if None, cutoff set as mean +- 2*sd")
    parser.add_argument('-k', '--mapq', type=int, default=20,
        help="minimal mapping quality (include)")
    parser.add_argument('-l', '--nmmax', type=int, default=1,
        help="maximal number of mismatches (include)")
    
    parser.add_argument('-p', '--downsample', type=int, default=10,
        help="the number of coverage downsampled (default by 10x)")


    parser.add_argument('-n', '--bpcount', type=int, default=5,
        help="# clip reads for a breakpoint to include in analysis")
    parser.add_argument('-m', '--juncread', type=int, default=10,
        help="# clip reads for a breakpoint pair to include in analysis")

    parser.add_argument('--max_n_breakpoint', type=int, default=500,
        help="max # of breakpoints to included in the analysis, if the \
            sequence depth is too high, the clip points will be too many \
            in this case, only the top N breakpoints will be analyzed \
            if tie @ N all breakpoints <= counts @ N will be removed")

    parser.add_argument('-d', '--segmode', default='standard',
        help='''
            segmentation mode --
            'standard' : calculate raw read counts in target bins,
                         used for data with low coverage bias,
                         such as ChIP-seq input, WGS.
            'bias' : calculate smoothed read counts in target bins,
                     used for data with coverage bias,
                     such as ChIP-seq test, ATAC-seq, Exome-seq, WES, MNase-seq, TartgetCapture.
            ''')
    parser.add_argument('--ega', action='store_true', required=False,
        help="infer the sub segment on amp")
    parser.add_argument('-s', '--sub-binsize', type=int, default=1000,
        help="sub bin size, for bias segmentation mode only")
    parser.add_argument('-q', '--segquant', default=0.5,
        help="calculate robust read counts in target genomic bins \
              by using quantiles of read counts in smaller bins, \
              for bias segmentation mode only")

    parser.add_argument('--cleanbp-cutoff', type=float, default=0.2,
        help="percentage cutoff of the CleanBP (breakpoint), \
              defined as the ClipDepth/Depth >= perc")  

    parser.add_argument('--only-keep-cleanbp', default=True,
        help="remove non CleanBP for segmentation")

    parser.add_argument('--SA_with_nm', action='store_true', required=False,
        help="use NM mismatch values in SA tags when filtering supplementary alignments")
    
    parser.add_argument('--subseg', action='store_true', required=False,
        help="infer the sub segment on amp")
    
    parser.add_argument('--num_chrom', default = None,
        help="infer the sub segment on amp")
    
    parser.add_argument('--method', default = 'both',
        help="infer the sub segment on amp")
    
    parser.add_argument('--rm_amp_df', action='store_true', required = False,
        help="infer the sub segment on amp")
    
    # parser.add_argument('--seg_len', type=int, default=9000000,
    # help="infer the sub segment on amp")

    parser.add_argument('--run_from_pdat', type = int, default = 0,
        help="run ask from saved pdat, resume run from k + 1 step")   #?????????????
    
    parser.add_argument('--knn', type = int, default = 3,
        help="run ask from saved pdat, resume run from k + 1 step")   #?????????????

    parser.add_argument('--first_filter', action='store_true', required=False,
        help="infer the sub segment on amp")
    
    parser.add_argument('--second_filter', action='store_true', required=False,
        help="infer the sub segment on amp")
    
    parser.add_argument('--third_filter', action='store_true', required=False,
        help="infer the sub segment on amp")
    
    return parser.parse_args()


#------------------------------------------------------------------------------#
def process_args(args):
    """ post process of arguments
    """
    #@ output file prefix
    if args.outprefix is None:
        args.outprefix = args.bamfile.replace('.bam', '')

    #@ set genome related files
    ask_files = resolve_ask_annotation_files(args.genome)
    args.blfile = str(ask_files["blfile"]) if ask_files["blfile"] is not None else None
    args.genefile = str(ask_files["genefile"]) if ask_files["genefile"] is not None else None
    args.sefile = str(ask_files["sefile"]) if ask_files["sefile"] is not None else None
    args.gsfile = str(ask_files["gsfile"]) if ask_files["gsfile"] is not None else None
    args.cgfile = str(ask_files["cgfile"]) if ask_files["cgfile"] is not None else None
    args.biasfile = str(ask_files["biasfile"]) if ask_files["biasfile"] is not None else None

    #@ create base dir of output files
    ask_paths = prepare_ask_output_paths(args.outprefix)
    args.outfig = str(ask_paths["outfig"])

    #@ set output file names
    args.output_stats     = str(ask_paths["output_stats"])
    args.output_cnamp     = str(ask_paths["output_cnamp"])
    args.output_cnseg     = str(ask_paths["output_cnseg"])

    args.output_bpcand    = str(ask_paths["output_bpcand"])
    args.output_bpduo     = str(ask_paths["output_bpduo"])
    args.output_bppair    = str(ask_paths["output_bppair"])
    args.output_seg       = str(ask_paths["output_seg"])
    args.output_circ      = str(ask_paths["output_circ"])
    args.output_line      = str(ask_paths["output_line"])
    args.output_clip      = str(ask_paths["output_clip"])
    args.output_bincnt    = str(ask_paths["output_bincnt"])
    args.output_binnorm   = str(ask_paths["output_binnorm"])
    args.output_align     = str(ask_paths["output_align"])
    args.output_align_dir = str(ask_paths["output_align_dir"])
    args.output_circ_stat = str(ask_paths["output_circ_stat"])

    args.output_pdat_1    = str(ask_paths["output_pdat_1"])
    args.output_pdat_2    = str(ask_paths["output_pdat_2"])
    args.output_pdat_3    = str(ask_paths["output_pdat_3"])
    args.output_pdat_4    = str(ask_paths["output_pdat_4"])

    return args


#------------------------------------------------------------------------------#
def main():
    #--------------------------------------------------------------------------#
    # set start time
    #--------------------------------------------------------------------------#
    startTime = time.time()


    #--------------------------------------------------------------------------#
    # get arguments
    #--------------------------------------------------------------------------#
    args = get_args()
    args = process_args(args)
    

    #--------------------------------------------------------------------------#
    # load pdat
    #--------------------------------------------------------------------------#
    if int(args.run_from_pdat) >= 1 and os.path.isfile(args.output_pdat_1):
        try:
            bp_all, clip_bg, bin_count, bp_duo_bam, bamfile = pd.read_pickle(args.output_pdat_1)
            if type(bamfile) == float:
                bp_all, clip_bg, bin_count, bp_duo_bam, bamfile = ask_core.process_alignment(
                args.bamfile, gsfile = args.gsfile, binsize = args.binsize,
                mapq = args.mapq, nmmax = args.nmmax,
                mode = args.segmode, sub_binsize = args.sub_binsize,
                seg_robost_quant = args.segquant, SA_with_nm = args.SA_with_nm, downsample = args.downsample)
                # output results
                bin_count.to_csv(args.output_bincnt, sep='\t', index=False)
                clip_bg.to_csv(args.output_clip, sep='\t', index=False, header=False)

                # save pdat
                pdat = [bp_all, clip_bg, bin_count, bp_duo_bam, bamfile]
                with open(args.output_pdat_1, "wb") as f:
                    pickle.dump(pdat, f)

                # output log
                print('alignment process - done \
                    - {0:0.1f} seconds\n'.format(time.time() - startTime))
        except:
            try:
                bp_all, clip_bg, bin_count, bp_duo_bam = pd.read_pickle(args.output_pdat_1)
                bamfile = args.bamfile
            except:
                bp_all, clip_bg, bin_count, bp_duo_bam, bamfile = pd.read_pickle(args.output_pdat_1)

    if int(args.run_from_pdat) >= 2 and os.path.isfile(args.output_pdat_2):
        cn_amp, cn_seg, bin_norm = pd.read_pickle(args.output_pdat_2)

    if int(args.run_from_pdat) >= 3 and os.path.isfile(args.output_pdat_3):
        bp_duo, bp_cand_stats = pd.read_pickle(args.output_pdat_3)

    if int(args.run_from_pdat) >= 4 and os.path.isfile(args.output_pdat_4):
        circ_anno, line_anno, bp_pair, seg = pd.read_pickle(args.output_pdat_4)


    #--------------------------------------------------------------------------#
    # step 1 : process bam file to generate bin counts and clip reads
    #--------------------------------------------------------------------------#
    if 'bp_all' not in locals(): # and not os.path.exists(args.output_pdat_1)
        # run module
        bp_all, clip_bg, bin_count, bp_duo_bam, bamfile = ask_core.process_alignment(
            args.bamfile, gsfile = args.gsfile, binsize = args.binsize,
            mapq = args.mapq, nmmax = args.nmmax,
            mode = args.segmode, sub_binsize = args.sub_binsize,
            seg_robost_quant = args.segquant, SA_with_nm = args.SA_with_nm, downsample = args.downsample)


        # output results
        bin_count.to_csv(args.output_bincnt, sep='\t', index=False)
        clip_bg.to_csv(args.output_clip, sep='\t', index=False, header=False)

        # save pdat
        pdat = [bp_all, clip_bg, bin_count, bp_duo_bam, bamfile]
        with open(args.output_pdat_1, "wb") as f:
            pickle.dump(pdat, f)

        # output log
        print('alignment process - done \
            - {0:0.1f} seconds\n'.format(time.time() - startTime))


    #--------------------------------------------------------------------------#
    # step 2 : identify amplified segments
    #--------------------------------------------------------------------------#
    if 'cn_amp' not in locals(): #and not os.path.exists(args.output_pdat_2)
        # run module
        cn_amp, cn_seg, bin_norm = \
            ask_core.detect_amplified_segment(
                bin_count, bp_all,
                args.blfile, args.genefile, args.gsfile, args.cgfile,
                biasfile = args.biasfile,
                binsize = args.binsize, min_cn = args.mincn)

        # output results
        cn_amp.to_csv(args.output_cnamp, sep='\t', index=False)
        cn_seg.to_csv(args.output_cnseg, sep='\t', index=False)
        bin_norm.to_csv(args.output_binnorm, sep='\t', index=False)

        # save pdat
        pdat = [cn_amp, cn_seg, bin_norm]
        with open(args.output_pdat_2, "wb") as f:
            pickle.dump(pdat, f)

        # output log
        print('detect amplified segments - done \
            - {0:0.1f} seconds\n'.format(time.time() - startTime))

    
    #--------------------------------------------------------------------------#
    # step 3 : identify breakpoint pairs
    #--------------------------------------------------------------------------#
    if 'bp_duo' not in locals():
        # run module
        bp_duo, bp_cand_stats = ask_core.detect_bp_pair(
            bamfile, bp_duo_bam,  bp_all, cn_amp, args.blfile,
            binsize = args.binsize, bp_min_clip = args.bpcount,
            mapq = args.mapq, nmmax = args.nmmax,
            max_n_bp = args.max_n_breakpoint,
            clean_bp_perc = args.cleanbp_cutoff,
            only_keep_clean_bp = args.only_keep_cleanbp,
            bp_pair_info_file = args.output_align, num_chrom = args.num_chrom,
            way = args.method)  # bp_pair_info_file can remove

        # output results
        bp_cand_stats.to_csv(args.output_bpcand, sep='\t', index=False)
        bp_duo.to_csv(args.output_bpduo, sep='\t', index=False)

        # save pdat
        pdat = [bp_duo, bp_cand_stats]
        with open(args.output_pdat_3, "wb") as f:
            pickle.dump(pdat, f)

        # output log
        print('detect breakpoint pairs - done \
            - {0:0.1f} seconds\n'.format(time.time() - startTime))


    #--------------------------------------------------------------------------#
    # step 4 : construct amplicons
    #--------------------------------------------------------------------------#
    if 'circ_anno' not in locals():
        # run module
        circ_anno, line_anno, bp_pair, seg, circ_score = ask_core.construct_amplicon(
            bp_duo, bp_cand_stats, cn_amp, bin_norm, args.genefile, args.sefile, args.cgfile, 
            segment_restrict = False,
            min_junc_cnt = args.juncread, subseg = args.subseg, rm_amp_df = args.rm_amp_df,
            first_filter = args.first_filter, second_filter = args.second_filter, third_filter = args.third_filter,
            knn = args.knn, saveseg = args.output_seg, savebp_bp_pair = args.output_bppair, EGA=args.ega)

        # output results
        bp_pair = clean_barcode_columns(bp_pair)
        circ_anno.to_csv(args.output_circ, sep='\t', index=False)
        line_anno.to_csv(args.output_line, sep='\t', index=False)
        bp_pair.to_csv(args.output_bppair, sep='\t', index=False)
        seg.to_csv(args.output_seg, sep='\t', index=False)
        write_sc_matrices_if_single_cell(
            bp_pair,
            circ_anno,
            f"{args.outprefix}_ask_sc",
            bam_path=bamfile,
            mapq=args.mapq,
        )

  
        # output breakpoint pair alignment
        ask_core.output_bppair_alignment(bp_pair, bamfile, args.output_align_dir, circ_anno)

        # save pdat
        pdat = [circ_anno, line_anno, bp_pair, seg]
        with open(args.output_pdat_4, "wb") as f:
            pickle.dump(pdat, f)

        # output log
        print('construct amplicons - done \
            - {0:0.1f} seconds\n'.format(time.time() - startTime))

    if not circ_anno.empty:
        try:
            # circ_stat = ask.score_circ(circ_anno, bin_norm, binsize = 10000)
            circ_score.to_csv(args.output_circ_stat, sep='\t', index=False)
        except:
            print('ask.score_circ - error \
            - {0:0.1f} seconds\n'.format(time.time() - startTime))
    #--------------------------------------------------------------------------#
    # step 5 : plot amplicons
    #--------------------------------------------------------------------------#
    # run module
    plot_ask_amplicons(
        ask_core,
        circ_anno,
        line_anno,
        cn_amp,
        args.genefile,
        args.sefile,
        bin_norm,
        fig_dir=args.outfig,
        binsize=args.binsize,
        plot_n=5,
        fig_width=15,
        fontsize=12,
        ext=0.3,
        start_time=startTime,
        clean_old_pdf=True,
    )


    #--------------------------------------------------------------------------#
    # output stats
    #--------------------------------------------------------------------------#
    # output statistics table
    write_ask_stats(args.output_stats, cn_amp, bp_cand_stats, bp_duo, circ_anno, line_anno)

    print('All - done - {} seconds\n'.format(time.time() - startTime))
    if args.subseg:
        print(f'seg is {args.subseg}')
    else:
        print(f'seg is {args.subseg}')
        print(0)


#------------------------------------------------------------------------------#
if __name__ == '__main__':
    main()
